services:
  live:
    image: ghcr.io/slowlydev/f1-dash-live:latest
    restart: unless-stopped
    ports:
      - 9206:4000
    environment:
      - ORIGIN=https://f1-dash.arpaneting.es
      - LIVE_BACKEND_ADDRESS=live:4000
      - RUST_LOG="live=debug"

  api:
    image: ghcr.io/slowlydev/f1-dash-api:latest
    restart: unless-stopped
#    ports:
#      - 4001:4001
    environment:
      - ORIGIN=https://f1-dash.arpaneting.es
      - API_BACKEND_ADDRESS=api:4001
      - RUST_LOG="api=debug"

  frontend:
    image: ghcr.io/slowlydev/f1-dash:latest
    restart: unless-stopped
    ports:
      - 9205:3000
    depends_on:
      - api
      - live
    environment:
      - NEXT_PUBLIC_LIVE_URL=https://api-f1-dash.arpaneting.es
      - API_URL=http://api:4001
      - DISABLE_IFRAME=1
      - TRACKING_ID=G-3ZKX0JY1QW
      - TRACKING_URL=https://base.slowly.dev/rep.js
      - NEXT_PUBLIC_MAP_KEY=lcgTreisBzMYLrFFSTK2